name: Post Combined Lessons Image (4:15 on Wednesday)

on:
  schedule:
    - cron: '15 16 * * WED'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Post Combined lesson Image
        run: |
          curl -X POST \
          --url '${{ secrets.APP_URL }}/api/publish' \
          -H "Content-Type: application/json" \
          -H 'Authorization: Bearer ${{ secrets.API_ACCESS_KEY }}' \
          -d '{"combined":true}'
